import tkinter as tk
import tkinter.font as tkFont
from tkinter.ttk import *
from database_sql import *
from functions import *
from tkcalendar import *
from persons_table_edit import *
from jobs_table_edit import *
from educations_table_edit import *
from departments_table_edit import *
from strings_table_edit import *
